import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { detectLanIp, LOCAL_SUPABASE, PORTS, urlsFor } from "./lan.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ip = process.env.LAN_IP || detectLanIp();
const urls = urlsFor(ip);

function write(rel, body) {
  const dest = join(root, rel);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, body.endsWith("\n") ? body : `${body}\n`);
}

const banner = `# Generated by \`pnpm lan\` — do not edit by hand.
# LAN_IP=${ip}  (override with LAN_IP=x.x.x.x pnpm lan)
`;

const shared = `${banner}
LAN_IP=${ip}
SUPABASE_URL=${urls.supabase}
SUPABASE_ANON_KEY=${LOCAL_SUPABASE.anonKey}
SUPABASE_SERVICE_ROLE_KEY=${LOCAL_SUPABASE.serviceRoleKey}
VISION_URL=${urls.vision}
RISK_URL=${urls.risk}
`;

write(
  ".env",
  `${shared}
ADMIN_URL=${urls.admin}
METRO_URL=${urls.metro}
SUPABASE_STUDIO_URL=${urls.studio}
`,
);

write(
  "apps/mobile/.env",
  `${banner}
EXPO_PUBLIC_LAN_IP=${ip}
EXPO_PUBLIC_SUPABASE_URL=${urls.supabase}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${LOCAL_SUPABASE.anonKey}
EXPO_PUBLIC_VISION_URL=${urls.vision}
EXPO_PUBLIC_RISK_URL=${urls.risk}
EXPO_PUBLIC_ADMIN_URL=${urls.admin}
EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
REACT_NATIVE_PACKAGER_HOSTNAME=${ip}
`,
);

write(
  "apps/admin/.env.local",
  `${banner}
NEXT_PUBLIC_LAN_IP=${ip}
NEXT_PUBLIC_SUPABASE_URL=${urls.supabase}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${LOCAL_SUPABASE.anonKey}
NEXT_PUBLIC_VISION_URL=${urls.vision}
NEXT_PUBLIC_RISK_URL=${urls.risk}
SUPABASE_SERVICE_ROLE_KEY=${LOCAL_SUPABASE.serviceRoleKey}
SUPABASE_URL=http://127.0.0.1:${PORTS.supabaseApi}
VISION_URL=http://127.0.0.1:${PORTS.vision}
RISK_URL=http://127.0.0.1:${PORTS.risk}
`,
);

write("services/vision/.env", `${banner}HOST=0.0.0.0\nPORT=${PORTS.vision}\n`);
write("services/risk/.env", `${banner}HOST=0.0.0.0\nPORT=${PORTS.risk}\n`);

console.log(`LAN IP  ${ip}`);
console.log(`Admin   ${urls.admin}`);
console.log(`Mobile  Expo --lan  (Metro ${urls.metro})`);
console.log(`API     ${urls.supabase}`);
console.log(`Vision  ${urls.vision}`);
console.log(`Risk    ${urls.risk}`);
console.log(`Studio  ${urls.studio}`);
