import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { detectLanIp, PORTS, urlsFor } from "./lan.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ip = process.env.LAN_IP || detectLanIp();
const urls = urlsFor(ip);

function write(rel, body) {
  const dest = join(root, rel);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, body.endsWith("\n") ? body : `${body}\n`);
}

const banner = `# Generated by \`pnpm lan\` — do not edit by hand.
# LAN_IP=${ip}  (override with LAN_IP=x.x.x.x pnpm lan)
`;

write(
  ".env",
  `${banner}
LAN_IP=${ip}
SUPABASE_URL=${urls.supabase}
FACE_URL=${urls.face}
ATTEST_API_URL=${urls.attest}
ADMIN_URL=${urls.admin}
SUPABASE_STUDIO_URL=${urls.studio}
`,
);

write(
  "apps/admin/.env.local",
  `${banner}
NEXT_PUBLIC_LAN_IP=${ip}
NEXT_PUBLIC_ATTEST_API_URL=${urls.attest}
`,
);

write("services/face/.env", `${banner}HOST=0.0.0.0\nPORT=${PORTS.face}\n`);

await import("./attest-env.mjs");

console.log(`LAN IP  ${ip}`);
console.log(`Console ${urls.admin}/triage`);
console.log(`Attest  ${urls.attest}  (edge function)`);
console.log(`Face    ${urls.face}`);
console.log(`API     ${urls.supabase}`);
console.log(`Studio  ${urls.studio}`);
